In [1]:
import numpy as np
import os

# Define the directory where the datasets are stored
data_dir = 'outputs'

# List all .npz files in the directory
npz_files = [f for f in os.listdir(data_dir) if f.endswith('.npz')]

datasets = {}

for file in npz_files:
    file_path = os.path.join(data_dir, file)
    # Load the dataset
    data = np.load(file_path)
    datasets[file] = {key: data[key] for key in data.files}
    
    print(f"Loaded {file}:")
    for key in data.files:
        print(f"  Shape of {key}: {data[key].shape}")
    print("-" * 20)


Loaded dataset_16x16.npz:
  Shape of puzzles: (10000, 16, 16)
  Shape of solutions: (10000, 16, 16)
  Shape of difficulty_metadata: (10000,)
  Shape of board_size: ()
--------------------
Loaded dataset_4x4.npz:
  Shape of puzzles: (1000, 4, 4)
  Shape of solutions: (1000, 4, 4)
  Shape of difficulty_metadata: (1000,)
  Shape of board_size: ()
--------------------
Loaded dataset_9x9.npz:
  Shape of puzzles: (10000, 9, 9)
  Shape of solutions: (10000, 9, 9)
  Shape of difficulty_metadata: (10000,)
  Shape of board_size: ()
--------------------


In [4]:
# Print a few example puzzles from the 9x9 dataset
if 'dataset_4x4.npz' in datasets:
    puzzles = datasets['dataset_4x4.npz']['puzzles']
    solutions = datasets['dataset_4x4.npz']['solutions']
    
    print("Example 4x4 Puzzles (First 2):")
    for i in range(2):
        print(f"Puzzle {i+1}:")
        print(puzzles[i])
        print(f"Solution {i+1}:")
        print(solutions[i])
        print("-" * 15)
else:
    print("dataset_4x4.npz not found in loaded datasets.")

Example 4x4 Puzzles (First 2):
Puzzle 1:
[[2 0 4 1]
 [0 0 2 0]
 [0 0 0 0]
 [4 0 0 0]]
Solution 1:
[[2 3 4 1]
 [1 4 2 3]
 [3 2 1 4]
 [4 1 3 2]]
---------------
Puzzle 2:
[[0 0 0 1]
 [0 4 0 0]
 [0 0 0 0]
 [2 0 3 0]]
Solution 2:
[[3 2 4 1]
 [1 4 2 3]
 [4 3 1 2]
 [2 1 3 4]]
---------------
